name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Generate build number
      run: echo "The build number $GITHUB_RUN_NUMBER 🏗"
    - name: Install dependencies
      run: npm install
    - name: Create .env
      run: |
        touch .env &&
        echo "ENVIRONMENT=${ENVIRONMENT}" > .env
        echo "PLATZI_FAKE_API_BASE_URL=${PLATZI_FAKE_API_BASE_URL}" >> .env
      env:
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        PLATZI_FAKE_API_BASE_URL: ${{secrets.PLATZI_FAKE_API_BASE_URL}}
    - name: Test 🧪
      run: npm run test
    - name: Build docker 🐳
      run: docker build . -t=javascript-asynchronism-kata:github-build-$GITHUB_RUN_NUMBER